import type {
  Company,
  Contact,
  ICP,
  EmailSequence,
  EmailDraft,
  DashboardStats,
  ActivityItem,
} from "@/types";

// ─── Companies ───────────────────────────────────────────────────────────────

const companyEnrichmentDefaults = {
  googleRating: null as number | null,
  googleReviewCount: null as number | null,
  reviewSentiment: null as string | null,
  crmDetected: null as string | null,
  crmName: null as string | null,
  websiteQuality: null as number | null,
  hasSsl: false,
  hasIdx: false,
  siteAge: null as string | null,
  techStack: [] as string[],
};

export const mockCompanies: Company[] = ([
  {
    id: "comp-001",
    name: "Velora AI",
    description:
      "Velora AI builds intelligent document processing pipelines that help enterprises automate data extraction from unstructured sources using proprietary LLM technology.",
    industry: "AI/ML",
    employeeCount: 85,
    employeeRange: "51-200",
    location: "San Francisco, CA",
    country: "US",
    website: "https://velora.ai",
    logoUrl: null,
    fundingStage: "series-a",
    fundingAmount: 18_000_000,
    lastFundingDate: "2025-09-15",
    technologies: ["Python", "React", "AWS", "PostgreSQL", "Docker", "Kubernetes"],
    news: [
      {
        id: "news-001",
        title: "Velora AI Raises $18M Series A to Scale Document Intelligence Platform",
        source: "TechCrunch",
        url: "https://techcrunch.com/2025/09/15/velora-ai-series-a",
        publishedAt: "2025-09-15T10:00:00Z",
        snippet:
          "Velora AI announced an $18M Series A round led by Sequoia Capital to expand its document processing platform into new verticals.",
      },
      {
        id: "news-002",
        title: "How Velora AI Is Disrupting Enterprise Document Workflows",
        source: "VentureBeat",
        url: "https://venturebeat.com/2025/11/02/velora-ai-enterprise",
        publishedAt: "2025-11-02T14:30:00Z",
        snippet:
          "The San Francisco startup has seen 300% growth in enterprise contracts over the past six months.",
      },
    ],
    contactIds: ["cont-001", "cont-002", "cont-003"],
    enrichedAt: "2025-12-01T08:00:00Z",
    matchedIcpId: "icp-001",
    createdAt: "2025-11-20T10:00:00Z",
  },
  {
    id: "comp-002",
    name: "Stackline",
    description:
      "Stackline provides a unified DevOps observability platform that correlates metrics, logs, and traces to reduce incident response time for engineering teams.",
    industry: "DevTools",
    employeeCount: 210,
    employeeRange: "201-500",
    location: "Seattle, WA",
    country: "US",
    website: "https://stackline.dev",
    logoUrl: null,
    fundingStage: "series-b",
    fundingAmount: 45_000_000,
    lastFundingDate: "2025-06-20",
    technologies: ["Go", "React", "Kubernetes", "Kafka", "Elasticsearch", "AWS"],
    news: [
      {
        id: "news-003",
        title: "Stackline Closes $45M Series B for DevOps Observability",
        source: "Forbes",
        url: "https://forbes.com/2025/06/20/stackline-series-b",
        publishedAt: "2025-06-20T09:00:00Z",
        snippet:
          "Stackline has secured $45M in Series B funding to expand its all-in-one observability platform for modern engineering teams.",
      },
      {
        id: "news-004",
        title: "Stackline Named a Leader in Gartner's APM Magic Quadrant",
        source: "Gartner",
        url: "https://gartner.com/2025/10/apm-magic-quadrant",
        publishedAt: "2025-10-15T12:00:00Z",
        snippet:
          "Stackline earned a Leader position in Gartner's 2025 Magic Quadrant for Application Performance Monitoring.",
      },
      {
        id: "news-005",
        title: "Why Engineering Teams Are Switching to Stackline",
        source: "The New Stack",
        url: "https://thenewstack.io/2025/12/stackline-review",
        publishedAt: "2025-12-01T08:00:00Z",
        snippet:
          "A growing number of SRE teams cite Stackline's correlated observability as a key differentiator over legacy monitoring tools.",
      },
    ],
    contactIds: ["cont-004", "cont-005", "cont-006"],
    enrichedAt: "2025-12-05T14:00:00Z",
    matchedIcpId: "icp-001",
    createdAt: "2025-11-18T09:00:00Z",
  },
  {
    id: "comp-003",
    name: "Finova",
    description:
      "Finova offers an API-first banking infrastructure that enables fintechs and neobanks to launch financial products in weeks instead of months.",
    industry: "FinTech",
    employeeCount: 340,
    employeeRange: "201-500",
    location: "New York, NY",
    country: "US",
    website: "https://finova.io",
    logoUrl: null,
    fundingStage: "series-c",
    fundingAmount: 92_000_000,
    lastFundingDate: "2025-03-10",
    technologies: ["TypeScript", "Node.js", "PostgreSQL", "AWS", "Terraform", "Redis"],
    news: [
      {
        id: "news-006",
        title: "Finova Secures $92M Series C to Expand Banking-as-a-Service",
        source: "Bloomberg",
        url: "https://bloomberg.com/2025/03/10/finova-series-c",
        publishedAt: "2025-03-10T11:00:00Z",
        snippet:
          "Finova's API-first approach to banking infrastructure has attracted 120+ fintech clients globally.",
      },
      {
        id: "news-007",
        title: "Finova Partners with Visa to Offer Instant Card Issuance",
        source: "Finextra",
        url: "https://finextra.com/2025/08/finova-visa-partnership",
        publishedAt: "2025-08-22T15:00:00Z",
        snippet:
          "The partnership enables Finova clients to issue virtual and physical Visa cards through a single API integration.",
      },
    ],
    contactIds: ["cont-007", "cont-008", "cont-009"],
    enrichedAt: "2025-12-02T10:00:00Z",
    matchedIcpId: "icp-002",
    createdAt: "2025-11-15T08:30:00Z",
  },
  {
    id: "comp-004",
    name: "ClearShield",
    description:
      "ClearShield is a next-generation endpoint security platform that uses behavioral analysis and AI to detect and neutralize zero-day threats in real time.",
    industry: "Cybersecurity",
    employeeCount: 150,
    employeeRange: "51-200",
    location: "Boston, MA",
    country: "US",
    website: "https://clearshield.io",
    logoUrl: null,
    fundingStage: "series-b",
    fundingAmount: 38_000_000,
    lastFundingDate: "2025-07-08",
    technologies: ["Rust", "Python", "AWS", "Kafka", "Elasticsearch", "Docker"],
    news: [
      {
        id: "news-008",
        title: "ClearShield Raises $38M to Advance AI-Powered Endpoint Security",
        source: "Dark Reading",
        url: "https://darkreading.com/2025/07/clearshield-series-b",
        publishedAt: "2025-07-08T10:00:00Z",
        snippet:
          "ClearShield's behavioral AI engine has demonstrated a 99.7% detection rate for zero-day threats in independent testing.",
      },
      {
        id: "news-009",
        title: "ClearShield Achieves SOC 2 Type II Certification",
        source: "SecurityWeek",
        url: "https://securityweek.com/2025/10/clearshield-soc2",
        publishedAt: "2025-10-20T09:00:00Z",
        snippet:
          "The certification underscores ClearShield's commitment to rigorous data protection and security practices.",
      },
    ],
    contactIds: ["cont-010", "cont-011", "cont-012"],
    enrichedAt: "2025-12-03T11:00:00Z",
    matchedIcpId: "icp-001",
    createdAt: "2025-11-22T14:00:00Z",
  },
  {
    id: "comp-005",
    name: "Nurtura Health",
    description:
      "Nurtura Health provides a patient engagement platform that helps healthcare providers deliver personalized care plans, remote monitoring, and automated follow-ups.",
    industry: "HealthTech",
    employeeCount: 95,
    employeeRange: "51-200",
    location: "Austin, TX",
    country: "US",
    website: "https://nurturahealth.com",
    logoUrl: null,
    fundingStage: "series-a",
    fundingAmount: 22_000_000,
    lastFundingDate: "2025-05-14",
    technologies: ["React", "Node.js", "MongoDB", "AWS", "GraphQL", "Docker"],
    news: [
      {
        id: "news-010",
        title: "Nurtura Health Raises $22M to Transform Patient Engagement",
        source: "MobiHealthNews",
        url: "https://mobihealthnews.com/2025/05/nurtura-series-a",
        publishedAt: "2025-05-14T10:00:00Z",
        snippet:
          "Nurtura Health's platform is used by over 200 healthcare providers across 15 states.",
      },
      {
        id: "news-011",
        title: "Nurtura Health Integrates with Epic EHR System",
        source: "Healthcare IT News",
        url: "https://healthcareitnews.com/2025/09/nurtura-epic-integration",
        publishedAt: "2025-09-30T13:00:00Z",
        snippet:
          "The integration allows providers to sync patient engagement data directly with their Epic electronic health records.",
      },
    ],
    contactIds: ["cont-013", "cont-014", "cont-015"],
    enrichedAt: "2025-12-04T09:30:00Z",
    matchedIcpId: null,
    createdAt: "2025-11-25T11:00:00Z",
  },
  {
    id: "comp-006",
    name: "Amplifi Data",
    description:
      "Amplifi Data is a customer data platform (CDP) that unifies first-party data across channels and enables real-time audience segmentation for B2B marketers.",
    industry: "MarTech",
    employeeCount: 120,
    employeeRange: "51-200",
    location: "Denver, CO",
    country: "US",
    website: "https://amplifidata.com",
    logoUrl: null,
    fundingStage: "series-a",
    fundingAmount: 15_000_000,
    lastFundingDate: "2025-04-18",
    technologies: ["TypeScript", "Next.js", "Snowflake", "AWS", "Kafka", "Redis"],
    news: [
      {
        id: "news-012",
        title: "Amplifi Data Raises $15M to Unify B2B Customer Data",
        source: "MarTech Today",
        url: "https://martechtoday.com/2025/04/amplifi-data-series-a",
        publishedAt: "2025-04-18T10:00:00Z",
        snippet:
          "Amplifi Data's real-time CDP processes over 2 billion events per day for its enterprise clients.",
      },
      {
        id: "news-013",
        title: "Amplifi Data Launches AI-Powered Audience Segmentation",
        source: "AdExchanger",
        url: "https://adexchanger.com/2025/10/amplifi-ai-segmentation",
        publishedAt: "2025-10-05T14:00:00Z",
        snippet:
          "The new feature uses machine learning to automatically identify high-value audience segments from first-party data.",
      },
      {
        id: "news-014",
        title: "How Amplifi Data Helped a Fortune 500 Retailer Boost Conversions 40%",
        source: "Marketing Dive",
        url: "https://marketingdive.com/2025/11/amplifi-case-study",
        publishedAt: "2025-11-12T08:00:00Z",
        snippet:
          "By unifying data across 12 marketing channels, the retailer achieved a 40% lift in conversion rates within 90 days.",
      },
    ],
    contactIds: ["cont-016", "cont-017", "cont-018"],
    enrichedAt: "2025-12-01T16:00:00Z",
    matchedIcpId: "icp-002",
    createdAt: "2025-11-19T13:00:00Z",
  },
  {
    id: "comp-007",
    name: "Nimbus Cloud",
    description:
      "Nimbus Cloud offers a multi-cloud cost optimization platform that helps engineering teams identify waste, right-size infrastructure, and automate savings.",
    industry: "Cloud Infrastructure",
    employeeCount: 65,
    employeeRange: "51-200",
    location: "London, UK",
    country: "UK",
    website: "https://nimbuscloud.io",
    logoUrl: null,
    fundingStage: "seed",
    fundingAmount: 8_500_000,
    lastFundingDate: "2025-08-01",
    technologies: ["Go", "React", "Terraform", "AWS", "Google Cloud", "Azure", "Kubernetes"],
    news: [
      {
        id: "news-015",
        title: "Nimbus Cloud Closes $8.5M Seed Round for Multi-Cloud Cost Optimization",
        source: "EU-Startups",
        url: "https://eu-startups.com/2025/08/nimbus-cloud-seed",
        publishedAt: "2025-08-01T09:00:00Z",
        snippet:
          "The London-based startup helps companies save an average of 35% on cloud spend without sacrificing performance.",
      },
      {
        id: "news-016",
        title: "Nimbus Cloud Adds Azure Support to Its Cost Optimization Engine",
        source: "InfoQ",
        url: "https://infoq.com/2025/11/nimbus-azure-support",
        publishedAt: "2025-11-18T12:00:00Z",
        snippet:
          "With Azure support, Nimbus Cloud now covers all three major cloud providers in a single dashboard.",
      },
    ],
    contactIds: ["cont-019", "cont-020", "cont-021"],
    enrichedAt: "2025-12-05T10:00:00Z",
    matchedIcpId: "icp-001",
    createdAt: "2025-11-28T08:00:00Z",
  },
  {
    id: "comp-008",
    name: "TalentForge",
    description:
      "TalentForge is an AI-powered talent intelligence platform that helps HR teams source, assess, and hire top engineering talent through skills-based matching.",
    industry: "HR Tech",
    employeeCount: 45,
    employeeRange: "11-50",
    location: "Toronto, Canada",
    country: "Canada",
    website: "https://talentforge.io",
    logoUrl: null,
    fundingStage: "seed",
    fundingAmount: 6_000_000,
    lastFundingDate: "2025-10-22",
    technologies: ["Python", "React", "PostgreSQL", "Docker", "FastAPI", "AWS"],
    news: [
      {
        id: "news-017",
        title: "TalentForge Raises $6M to Reinvent Technical Hiring with AI",
        source: "BetaKit",
        url: "https://betakit.com/2025/10/talentforge-seed",
        publishedAt: "2025-10-22T10:00:00Z",
        snippet:
          "TalentForge's AI matching engine has reduced time-to-hire by 60% for early adopter companies.",
      },
      {
        id: "news-018",
        title: "TalentForge Launches Skills Graph for Engineering Teams",
        source: "HR Tech Outlook",
        url: "https://hrtechoutlook.com/2025/12/talentforge-skills-graph",
        publishedAt: "2025-12-02T11:00:00Z",
        snippet:
          "The Skills Graph maps technical competencies across an organization, identifying skill gaps and internal mobility opportunities.",
      },
    ],
    contactIds: ["cont-022", "cont-023", "cont-024"],
    enrichedAt: "2025-12-06T08:30:00Z",
    matchedIcpId: null,
    createdAt: "2025-11-30T09:00:00Z",
  },
  {
    id: "comp-009",
    name: "DataWeave",
    description:
      "DataWeave is a competitive intelligence platform that aggregates and analyzes publicly available data to give e-commerce brands real-time pricing, product, and MAP compliance insights.",
    industry: "Data Analytics",
    employeeCount: 280,
    employeeRange: "201-500",
    location: "Bangalore, India",
    country: "India",
    website: "https://dataweave.com",
    logoUrl: null,
    fundingStage: "series-b",
    fundingAmount: 30_000_000,
    lastFundingDate: "2025-01-25",
    technologies: ["Python", "Databricks", "Snowflake", "React", "AWS", "Kafka"],
    news: [
      {
        id: "news-019",
        title: "DataWeave Secures $30M Series B for E-commerce Intelligence",
        source: "YourStory",
        url: "https://yourstory.com/2025/01/dataweave-series-b",
        publishedAt: "2025-01-25T10:00:00Z",
        snippet:
          "DataWeave's platform monitors over 500 million product listings across 20,000+ e-commerce websites globally.",
      },
      {
        id: "news-020",
        title: "DataWeave Expands into European Market with New London Office",
        source: "Economic Times",
        url: "https://economictimes.com/2025/09/dataweave-europe",
        publishedAt: "2025-09-10T08:00:00Z",
        snippet:
          "The expansion targets European retailers seeking competitive pricing intelligence and MAP compliance monitoring.",
      },
    ],
    contactIds: ["cont-025", "cont-026", "cont-027"],
    enrichedAt: "2025-12-04T15:00:00Z",
    matchedIcpId: "icp-002",
    createdAt: "2025-11-16T07:00:00Z",
  },
  {
    id: "comp-010",
    name: "GreenGrid",
    description:
      "GreenGrid develops smart energy management software for commercial buildings, using IoT sensors and AI to reduce energy consumption by up to 40%.",
    industry: "Clean Energy",
    employeeCount: 30,
    employeeRange: "11-50",
    location: "Berlin, Germany",
    country: "Germany",
    website: "https://greengrid.energy",
    logoUrl: null,
    fundingStage: "pre-seed",
    fundingAmount: 2_500_000,
    lastFundingDate: "2025-11-05",
    technologies: ["TypeScript", "React", "Node.js", "MongoDB", "Docker", "Google Cloud"],
    news: [
      {
        id: "news-021",
        title: "GreenGrid Emerges from Stealth with $2.5M to Decarbonize Commercial Buildings",
        source: "CleanTechnica",
        url: "https://cleantechnica.com/2025/11/greengrid-launch",
        publishedAt: "2025-11-05T10:00:00Z",
        snippet:
          "GreenGrid's IoT-powered platform has already been deployed in 50 commercial buildings across Germany.",
      },
      {
        id: "news-022",
        title: "Berlin Startup GreenGrid Wins EU Green Innovation Award",
        source: "EU Innovation Council",
        url: "https://eic.ec.europa.eu/2025/12/greengrid-award",
        publishedAt: "2025-12-01T14:00:00Z",
        snippet:
          "GreenGrid was recognized for its innovative approach to reducing commercial building energy waste through AI-driven optimization.",
      },
    ],
    contactIds: ["cont-028", "cont-029", "cont-030"],
    enrichedAt: "2025-12-06T12:00:00Z",
    matchedIcpId: null,
    createdAt: "2025-12-01T10:00:00Z",
  },
] as Omit<Company, keyof typeof companyEnrichmentDefaults>[]).map((c) => ({ ...companyEnrichmentDefaults, ...c }));

// ─── Contacts ────────────────────────────────────────────────────────────────

const contactPipelineDefaults = {
  emailStatus: "unverified" as const,
  emailConfidence: 0,
  emailSource: "scraped",
  validatedAt: null as string | null,
  leadScore: 0,
  leadTier: "cold" as const,
  icpFitScore: 0,
  timingScore: 0,
  dataQualityScore: 0,
  scoredAt: null as string | null,
  contactStatus: "new" as const,
  suppressedAt: null as string | null,
  suppressReason: null as string | null,
  lastContactedAt: null as string | null,
};

export const mockContacts: Contact[] = ([
  // Velora AI
  {
    id: "cont-001",
    companyId: "comp-001",
    companyName: "Velora AI",
    firstName: "Sarah",
    lastName: "Chen",
    fullName: "Sarah Chen",
    title: "CEO & Co-Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "sarah.chen@velora.ai",
    personalEmail: null,
    workPhone: "+1-415-555-0101",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/sarahchen",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-001",
        title: "The Future of Document AI: A Conversation with Velora's CEO",
        source: "AI Weekly",
        url: "https://aiweekly.com/2025/10/sarah-chen-interview",
        publishedAt: "2025-10-15T10:00:00Z",
        snippet:
          "Sarah Chen discusses how LLMs are transforming enterprise document processing and the road ahead for Velora AI.",
      },
    ],
    enrichedAt: "2025-12-01T08:00:00Z",
    createdAt: "2025-11-20T10:00:00Z",
  },
  {
    id: "cont-002",
    companyId: "comp-001",
    companyName: "Velora AI",
    firstName: "Marcus",
    lastName: "Rivera",
    fullName: "Marcus Rivera",
    title: "VP of Engineering",
    department: "Engineering",
    photoUrl: null,
    workEmail: "marcus.rivera@velora.ai",
    personalEmail: null,
    workPhone: "+1-415-555-0102",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/marcusrivera",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-01T08:00:00Z",
    createdAt: "2025-11-20T10:00:00Z",
  },
  {
    id: "cont-003",
    companyId: "comp-001",
    companyName: "Velora AI",
    firstName: "Priya",
    lastName: "Nair",
    fullName: "Priya Nair",
    title: "Head of Product",
    department: "Product",
    photoUrl: null,
    workEmail: "priya.nair@velora.ai",
    personalEmail: null,
    workPhone: null,
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/priyanair",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-01T08:00:00Z",
    createdAt: "2025-11-20T10:00:00Z",
  },
  // Stackline
  {
    id: "cont-004",
    companyId: "comp-002",
    companyName: "Stackline",
    firstName: "James",
    lastName: "Whitfield",
    fullName: "James Whitfield",
    title: "CTO & Co-Founder",
    department: "Engineering",
    photoUrl: null,
    workEmail: "james.whitfield@stackline.dev",
    personalEmail: null,
    workPhone: "+1-206-555-0201",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/jameswhitfield",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-002",
        title: "Building Correlated Observability at Scale",
        source: "InfoQ",
        url: "https://infoq.com/2025/08/james-whitfield-observability",
        publishedAt: "2025-08-20T10:00:00Z",
        snippet:
          "Stackline CTO James Whitfield shares the architecture behind their correlated observability engine.",
      },
    ],
    enrichedAt: "2025-12-05T14:00:00Z",
    createdAt: "2025-11-18T09:00:00Z",
  },
  {
    id: "cont-005",
    companyId: "comp-002",
    companyName: "Stackline",
    firstName: "Emily",
    lastName: "Park",
    fullName: "Emily Park",
    title: "VP of Sales",
    department: "Sales",
    photoUrl: null,
    workEmail: "emily.park@stackline.dev",
    personalEmail: null,
    workPhone: "+1-206-555-0202",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/emilypark",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-05T14:00:00Z",
    createdAt: "2025-11-18T09:00:00Z",
  },
  {
    id: "cont-006",
    companyId: "comp-002",
    companyName: "Stackline",
    firstName: "David",
    lastName: "Okafor",
    fullName: "David Okafor",
    title: "Director of Customer Success",
    department: "Customer Success",
    photoUrl: null,
    workEmail: "david.okafor@stackline.dev",
    personalEmail: null,
    workPhone: null,
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/davidokafor",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-05T14:00:00Z",
    createdAt: "2025-11-18T09:00:00Z",
  },
  // Finova
  {
    id: "cont-007",
    companyId: "comp-003",
    companyName: "Finova",
    firstName: "Michael",
    lastName: "Torres",
    fullName: "Michael Torres",
    title: "CEO",
    department: "Executive",
    photoUrl: null,
    workEmail: "michael.torres@finova.io",
    personalEmail: null,
    workPhone: "+1-212-555-0301",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/michaeltorres",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-003",
        title: "Banking Infrastructure in 2026: Finova CEO Shares His Vision",
        source: "Finextra",
        url: "https://finextra.com/2025/11/michael-torres-interview",
        publishedAt: "2025-11-15T10:00:00Z",
        snippet:
          "Michael Torres discusses how API-first banking is enabling the next wave of financial innovation.",
      },
    ],
    enrichedAt: "2025-12-02T10:00:00Z",
    createdAt: "2025-11-15T08:30:00Z",
  },
  {
    id: "cont-008",
    companyId: "comp-003",
    companyName: "Finova",
    firstName: "Rachel",
    lastName: "Goldstein",
    fullName: "Rachel Goldstein",
    title: "VP of Engineering",
    department: "Engineering",
    photoUrl: null,
    workEmail: "rachel.goldstein@finova.io",
    personalEmail: null,
    workPhone: "+1-212-555-0302",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/rachelgoldstein",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-02T10:00:00Z",
    createdAt: "2025-11-15T08:30:00Z",
  },
  {
    id: "cont-009",
    companyId: "comp-003",
    companyName: "Finova",
    firstName: "Kevin",
    lastName: "Pham",
    fullName: "Kevin Pham",
    title: "Head of Partnerships",
    department: "Sales",
    photoUrl: null,
    workEmail: "kevin.pham@finova.io",
    personalEmail: null,
    workPhone: null,
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/kevinpham",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-02T10:00:00Z",
    createdAt: "2025-11-15T08:30:00Z",
  },
  // ClearShield
  {
    id: "cont-010",
    companyId: "comp-004",
    companyName: "ClearShield",
    firstName: "Alex",
    lastName: "Morgan",
    fullName: "Alex Morgan",
    title: "CEO & Co-Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "alex.morgan@clearshield.io",
    personalEmail: null,
    workPhone: "+1-617-555-0401",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/alexmorgan-cyber",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-004",
        title: "Zero-Day Defense: Inside ClearShield's AI-Driven Approach",
        source: "Dark Reading",
        url: "https://darkreading.com/2025/09/clearshield-ceo-interview",
        publishedAt: "2025-09-18T10:00:00Z",
        snippet:
          "Alex Morgan explains ClearShield's behavioral analysis approach to detecting and neutralizing zero-day threats.",
      },
    ],
    enrichedAt: "2025-12-03T11:00:00Z",
    createdAt: "2025-11-22T14:00:00Z",
  },
  {
    id: "cont-011",
    companyId: "comp-004",
    companyName: "ClearShield",
    firstName: "Jennifer",
    lastName: "Kim",
    fullName: "Jennifer Kim",
    title: "VP of Product",
    department: "Product",
    photoUrl: null,
    workEmail: "jennifer.kim@clearshield.io",
    personalEmail: null,
    workPhone: "+1-617-555-0402",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/jenniferkim",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-03T11:00:00Z",
    createdAt: "2025-11-22T14:00:00Z",
  },
  {
    id: "cont-012",
    companyId: "comp-004",
    companyName: "ClearShield",
    firstName: "Thomas",
    lastName: "Brennan",
    fullName: "Thomas Brennan",
    title: "Director of Sales",
    department: "Sales",
    photoUrl: null,
    workEmail: "thomas.brennan@clearshield.io",
    personalEmail: null,
    workPhone: "+1-617-555-0403",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/thomasbrennan",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-03T11:00:00Z",
    createdAt: "2025-11-22T14:00:00Z",
  },
  // Nurtura Health
  {
    id: "cont-013",
    companyId: "comp-005",
    companyName: "Nurtura Health",
    firstName: "Amanda",
    lastName: "Williams",
    fullName: "Amanda Williams",
    title: "CEO & Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "amanda.williams@nurturahealth.com",
    personalEmail: null,
    workPhone: "+1-512-555-0501",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/amandawilliams-health",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-005",
        title: "Transforming Patient Engagement: Q&A with Nurtura Health Founder",
        source: "MobiHealthNews",
        url: "https://mobihealthnews.com/2025/08/amanda-williams-qa",
        publishedAt: "2025-08-10T10:00:00Z",
        snippet:
          "Amanda Williams shares her vision for how technology can close the gap between providers and patients.",
      },
    ],
    enrichedAt: "2025-12-04T09:30:00Z",
    createdAt: "2025-11-25T11:00:00Z",
  },
  {
    id: "cont-014",
    companyId: "comp-005",
    companyName: "Nurtura Health",
    firstName: "Daniel",
    lastName: "Reyes",
    fullName: "Daniel Reyes",
    title: "CTO",
    department: "Engineering",
    photoUrl: null,
    workEmail: "daniel.reyes@nurturahealth.com",
    personalEmail: null,
    workPhone: "+1-512-555-0502",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/danielreyes",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-04T09:30:00Z",
    createdAt: "2025-11-25T11:00:00Z",
  },
  {
    id: "cont-015",
    companyId: "comp-005",
    companyName: "Nurtura Health",
    firstName: "Lisa",
    lastName: "Chang",
    fullName: "Lisa Chang",
    title: "Head of Marketing",
    department: "Marketing",
    photoUrl: null,
    workEmail: "lisa.chang@nurturahealth.com",
    personalEmail: null,
    workPhone: null,
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/lisachang",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-04T09:30:00Z",
    createdAt: "2025-11-25T11:00:00Z",
  },
  // Amplifi Data
  {
    id: "cont-016",
    companyId: "comp-006",
    companyName: "Amplifi Data",
    firstName: "Ryan",
    lastName: "Mitchell",
    fullName: "Ryan Mitchell",
    title: "CEO & Co-Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "ryan.mitchell@amplifidata.com",
    personalEmail: null,
    workPhone: "+1-720-555-0601",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/ryanmitchell",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-006",
        title: "Why First-Party Data Is the Future of B2B Marketing",
        source: "MarTech Today",
        url: "https://martechtoday.com/2025/07/ryan-mitchell-first-party-data",
        publishedAt: "2025-07-22T10:00:00Z",
        snippet:
          "Amplifi Data CEO Ryan Mitchell on why the deprecation of third-party cookies is a massive opportunity for B2B marketers.",
      },
    ],
    enrichedAt: "2025-12-01T16:00:00Z",
    createdAt: "2025-11-19T13:00:00Z",
  },
  {
    id: "cont-017",
    companyId: "comp-006",
    companyName: "Amplifi Data",
    firstName: "Natalie",
    lastName: "Brooks",
    fullName: "Natalie Brooks",
    title: "VP of Engineering",
    department: "Engineering",
    photoUrl: null,
    workEmail: "natalie.brooks@amplifidata.com",
    personalEmail: null,
    workPhone: "+1-720-555-0602",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/nataliebrooks",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-01T16:00:00Z",
    createdAt: "2025-11-19T13:00:00Z",
  },
  {
    id: "cont-018",
    companyId: "comp-006",
    companyName: "Amplifi Data",
    firstName: "Chris",
    lastName: "Duarte",
    fullName: "Chris Duarte",
    title: "Director of Data Science",
    department: "Data Science",
    photoUrl: null,
    workEmail: "chris.duarte@amplifidata.com",
    personalEmail: null,
    workPhone: null,
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/chrisduarte",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-01T16:00:00Z",
    createdAt: "2025-11-19T13:00:00Z",
  },
  // Nimbus Cloud
  {
    id: "cont-019",
    companyId: "comp-007",
    companyName: "Nimbus Cloud",
    firstName: "Oliver",
    lastName: "Hartley",
    fullName: "Oliver Hartley",
    title: "CEO & Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "oliver.hartley@nimbuscloud.io",
    personalEmail: null,
    workPhone: "+44-20-7555-0701",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/oliverhartley",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-007",
        title: "Cloud Cost Optimization: Nimbus CEO on Saving 35% Without Downgrading",
        source: "The Register",
        url: "https://theregister.com/2025/09/oliver-hartley-cloud-costs",
        publishedAt: "2025-09-25T10:00:00Z",
        snippet:
          "Oliver Hartley explains how Nimbus Cloud's algorithms identify waste that manual reviews consistently miss.",
      },
    ],
    enrichedAt: "2025-12-05T10:00:00Z",
    createdAt: "2025-11-28T08:00:00Z",
  },
  {
    id: "cont-020",
    companyId: "comp-007",
    companyName: "Nimbus Cloud",
    firstName: "Sophie",
    lastName: "Laurent",
    fullName: "Sophie Laurent",
    title: "Head of Product",
    department: "Product",
    photoUrl: null,
    workEmail: "sophie.laurent@nimbuscloud.io",
    personalEmail: null,
    workPhone: "+44-20-7555-0702",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/sophielaurent",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-05T10:00:00Z",
    createdAt: "2025-11-28T08:00:00Z",
  },
  {
    id: "cont-021",
    companyId: "comp-007",
    companyName: "Nimbus Cloud",
    firstName: "Ben",
    lastName: "Archer",
    fullName: "Ben Archer",
    title: "VP of Sales",
    department: "Sales",
    photoUrl: null,
    workEmail: "ben.archer@nimbuscloud.io",
    personalEmail: null,
    workPhone: "+44-20-7555-0703",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/benarcher",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-05T10:00:00Z",
    createdAt: "2025-11-28T08:00:00Z",
  },
  // TalentForge
  {
    id: "cont-022",
    companyId: "comp-008",
    companyName: "TalentForge",
    firstName: "Maya",
    lastName: "Kapoor",
    fullName: "Maya Kapoor",
    title: "CEO & Co-Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "maya.kapoor@talentforge.io",
    personalEmail: null,
    workPhone: "+1-416-555-0801",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/mayakapoor",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-008",
        title: "How AI Is Eliminating Bias in Technical Hiring",
        source: "Fast Company",
        url: "https://fastcompany.com/2025/11/maya-kapoor-talentforge",
        publishedAt: "2025-11-08T10:00:00Z",
        snippet:
          "Maya Kapoor discusses how TalentForge's skills-based approach reduces hiring bias while improving candidate quality.",
      },
    ],
    enrichedAt: "2025-12-06T08:30:00Z",
    createdAt: "2025-11-30T09:00:00Z",
  },
  {
    id: "cont-023",
    companyId: "comp-008",
    companyName: "TalentForge",
    firstName: "Ethan",
    lastName: "Walsh",
    fullName: "Ethan Walsh",
    title: "CTO",
    department: "Engineering",
    photoUrl: null,
    workEmail: "ethan.walsh@talentforge.io",
    personalEmail: null,
    workPhone: "+1-416-555-0802",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/ethanwalsh",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-06T08:30:00Z",
    createdAt: "2025-11-30T09:00:00Z",
  },
  {
    id: "cont-024",
    companyId: "comp-008",
    companyName: "TalentForge",
    firstName: "Rebecca",
    lastName: "Foster",
    fullName: "Rebecca Foster",
    title: "Head of Marketing",
    department: "Marketing",
    photoUrl: null,
    workEmail: "rebecca.foster@talentforge.io",
    personalEmail: null,
    workPhone: null,
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/rebeccafoster",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-06T08:30:00Z",
    createdAt: "2025-11-30T09:00:00Z",
  },
  // DataWeave
  {
    id: "cont-025",
    companyId: "comp-009",
    companyName: "DataWeave",
    firstName: "Arjun",
    lastName: "Mehta",
    fullName: "Arjun Mehta",
    title: "CEO & Co-Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "arjun.mehta@dataweave.com",
    personalEmail: null,
    workPhone: "+91-80-555-0901",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/arjunmehta",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-009",
        title: "Competitive Intelligence at Scale: DataWeave's Approach",
        source: "YourStory",
        url: "https://yourstory.com/2025/06/arjun-mehta-dataweave",
        publishedAt: "2025-06-15T10:00:00Z",
        snippet:
          "Arjun Mehta shares how DataWeave processes half a billion product listings to deliver actionable competitive insights.",
      },
    ],
    enrichedAt: "2025-12-04T15:00:00Z",
    createdAt: "2025-11-16T07:00:00Z",
  },
  {
    id: "cont-026",
    companyId: "comp-009",
    companyName: "DataWeave",
    firstName: "Sneha",
    lastName: "Rao",
    fullName: "Sneha Rao",
    title: "VP of Engineering",
    department: "Engineering",
    photoUrl: null,
    workEmail: "sneha.rao@dataweave.com",
    personalEmail: null,
    workPhone: "+91-80-555-0902",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/sneharao",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-04T15:00:00Z",
    createdAt: "2025-11-16T07:00:00Z",
  },
  {
    id: "cont-027",
    companyId: "comp-009",
    companyName: "DataWeave",
    firstName: "Patrick",
    lastName: "Sullivan",
    fullName: "Patrick Sullivan",
    title: "Head of North America Sales",
    department: "Sales",
    photoUrl: null,
    workEmail: "patrick.sullivan@dataweave.com",
    personalEmail: null,
    workPhone: "+1-646-555-0903",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/patricksullivan",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-04T15:00:00Z",
    createdAt: "2025-11-16T07:00:00Z",
  },
  // GreenGrid
  {
    id: "cont-028",
    companyId: "comp-010",
    companyName: "GreenGrid",
    firstName: "Lukas",
    lastName: "Weber",
    fullName: "Lukas Weber",
    title: "CEO & Co-Founder",
    department: "Executive",
    photoUrl: null,
    workEmail: "lukas.weber@greengrid.energy",
    personalEmail: null,
    workPhone: "+49-30-555-1001",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/lukasweber",
    facebookUrl: null,
    instagramUrl: null,
    articles: [
      {
        id: "art-010",
        title: "The Smart Building Revolution: GreenGrid Founder on Decarbonization",
        source: "CleanTechnica",
        url: "https://cleantechnica.com/2025/12/lukas-weber-interview",
        publishedAt: "2025-12-05T10:00:00Z",
        snippet:
          "Lukas Weber explains how IoT and AI can cut commercial building energy consumption by 40% or more.",
      },
    ],
    enrichedAt: "2025-12-06T12:00:00Z",
    createdAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "cont-029",
    companyId: "comp-010",
    companyName: "GreenGrid",
    firstName: "Anna",
    lastName: "Schneider",
    fullName: "Anna Schneider",
    title: "CTO",
    department: "Engineering",
    photoUrl: null,
    workEmail: "anna.schneider@greengrid.energy",
    personalEmail: null,
    workPhone: "+49-30-555-1002",
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/annaschneider",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-06T12:00:00Z",
    createdAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "cont-030",
    companyId: "comp-010",
    companyName: "GreenGrid",
    firstName: "Felix",
    lastName: "Braun",
    fullName: "Felix Braun",
    title: "Head of Business Development",
    department: "Sales",
    photoUrl: null,
    workEmail: "felix.braun@greengrid.energy",
    personalEmail: null,
    workPhone: null,
    personalPhone: null,
    linkedinUrl: "https://linkedin.com/in/felixbraun",
    facebookUrl: null,
    instagramUrl: null,
    articles: [],
    enrichedAt: "2025-12-06T12:00:00Z",
    createdAt: "2025-12-01T10:00:00Z",
  },
] as Omit<Contact, keyof typeof contactPipelineDefaults>[]).map((c) => ({ ...contactPipelineDefaults, ...c }));

// ─── ICP Profiles ────────────────────────────────────────────────────────────

export const mockICPs: ICP[] = [
  {
    id: "icp-001",
    name: "High-Growth B2B SaaS (Series A-B)",
    industries: ["SaaS", "DevTools", "Cloud Infrastructure", "Cybersecurity"],
    companySizeMin: 50,
    companySizeMax: 500,
    locations: ["San Francisco, CA", "New York, NY", "Seattle, WA", "Boston, MA", "London, UK"],
    technologies: ["React", "TypeScript", "AWS", "Kubernetes", "Docker"],
    fundingStages: ["series-a", "series-b"],
    revenueMin: 5_000_000,
    revenueMax: 50_000_000,
    keywords: ["B2B", "enterprise", "platform", "API", "developer tools"],
    createdAt: "2025-11-01T10:00:00Z",
    updatedAt: "2025-12-01T14:00:00Z",
  },
  {
    id: "icp-002",
    name: "Data-Driven Scale-Ups",
    industries: ["Data Analytics", "MarTech", "FinTech", "AI/ML"],
    companySizeMin: 100,
    companySizeMax: 1000,
    locations: [
      "San Francisco, CA",
      "New York, NY",
      "Denver, CO",
      "Bangalore, India",
      "London, UK",
    ],
    technologies: ["Python", "Snowflake", "Databricks", "Kafka", "AWS"],
    fundingStages: ["series-a", "series-b", "series-c"],
    revenueMin: 10_000_000,
    revenueMax: 100_000_000,
    keywords: ["data platform", "analytics", "intelligence", "machine learning", "CDP"],
    createdAt: "2025-11-10T12:00:00Z",
    updatedAt: "2025-12-03T09:00:00Z",
  },
];

// ─── Email Sequences ─────────────────────────────────────────────────────────

export const mockEmailSequences: EmailSequence[] = [
  {
    id: "seq-001",
    name: "Cold Outreach - Engineering Leaders",
    status: "active",
    steps: [
      {
        id: "step-001",
        order: 1,
        delayDays: 0,
        subject: "Quick question about {{companyName}}'s tech stack",
        body: "Hi {{firstName}},\n\nI noticed {{companyName}} is using {{industry}} solutions and recently made headlines with some exciting developments.\n\nI'm reaching out because we've helped similar companies streamline their workflows and I'd love to share how.\n\nWould you be open to a quick 15-minute chat this week?\n\nBest,\nFloeey Team",
        type: "initial",
      },
      {
        id: "step-002",
        order: 2,
        delayDays: 3,
        subject: "Re: Quick question about {{companyName}}'s tech stack",
        body: "Hi {{firstName}},\n\nJust wanted to follow up on my previous note. I know things get busy, especially at a growing company like {{companyName}}.\n\nI thought you might find it interesting that we recently helped a {{industry}} company reduce their lead qualification time by 60%.\n\nWould love to share more details if you're interested.\n\nBest,\nFloeey Team",
        type: "follow-up",
      },
      {
        id: "step-003",
        order: 3,
        delayDays: 5,
        subject: "One more thing, {{firstName}}",
        body: "Hi {{firstName}},\n\nI don't want to be a bother, so this will be my last note.\n\nIf streamlining your outbound process is ever a priority for {{companyName}}, I'd be happy to chat. No pressure at all.\n\nWishing you and the team continued success!\n\nBest,\nFloeey Team",
        type: "breakup",
      },
    ],
    enrolledContactIds: ["cont-001", "cont-004", "cont-010", "cont-019", "cont-022"],
    createdAt: "2025-11-15T10:00:00Z",
    updatedAt: "2025-12-06T08:00:00Z",
  },
  {
    id: "seq-002",
    name: "Warm Intro - Post Funding Round",
    status: "active",
    steps: [
      {
        id: "step-004",
        order: 1,
        delayDays: 0,
        subject: "Congrats on the funding, {{firstName}}!",
        body: "Hi {{firstName}},\n\nCongratulations to you and the {{companyName}} team on the recent funding round! That's a huge milestone.\n\nAs you scale, many teams in {{industry}} find that their outbound processes need to evolve. We've built something that might help.\n\nWould you be open to a brief conversation about how we could support {{companyName}}'s growth?\n\nBest,\nFloeey Team",
        type: "initial",
      },
      {
        id: "step-005",
        order: 2,
        delayDays: 4,
        subject: "Re: Congrats on the funding, {{firstName}}!",
        body: "Hi {{firstName}},\n\nJust circling back on my previous note. I know post-funding is an incredibly busy time.\n\nI'd love to show you a quick demo of how we help {{industry}} companies identify and engage their ideal customers more efficiently.\n\nAny chance you have 15 minutes this week or next?\n\nBest,\nFloeey Team",
        type: "follow-up",
      },
      {
        id: "step-006",
        order: 3,
        delayDays: 4,
        subject: "Timing not right? No worries, {{firstName}}",
        body: "Hi {{firstName}},\n\nI completely understand if the timing isn't right. Scaling a company after a funding round is no small feat.\n\nIf you'd ever like to explore how Floeey can help {{companyName}} grow its pipeline, my door is always open.\n\nWishing you the best!\n\nBest,\nFloeey Team",
        type: "follow-up",
      },
      {
        id: "step-007",
        order: 4,
        delayDays: 7,
        subject: "Last note from me, {{firstName}}",
        body: "Hi {{firstName}},\n\nThis is my final follow-up. I respect your time and don't want to crowd your inbox.\n\nIf {{companyName}} ever needs help with lead generation or outbound automation, feel free to reach out anytime.\n\nAll the best to you and the team!\n\nBest,\nFloeey Team",
        type: "breakup",
      },
    ],
    enrolledContactIds: ["cont-007", "cont-013", "cont-028"],
    createdAt: "2025-11-20T14:00:00Z",
    updatedAt: "2025-12-05T16:00:00Z",
  },
  {
    id: "seq-003",
    name: "Re-engagement - Past Conversations",
    status: "draft",
    steps: [
      {
        id: "step-008",
        order: 1,
        delayDays: 0,
        subject: "Things have changed at Floeey, {{firstName}}",
        body: "Hi {{firstName}},\n\nWe chatted a while back about how Floeey could help {{companyName}} with outbound. Since then, we've shipped some major improvements that I think would be really relevant to your team.\n\nWould you be up for a quick catch-up to see what's new?\n\nBest,\nFloeey Team",
        type: "initial",
      },
      {
        id: "step-009",
        order: 2,
        delayDays: 5,
        subject: "Quick update for {{companyName}}",
        body: "Hi {{firstName}},\n\nJust wanted to make sure my previous note didn't get lost. Here's a quick summary of what we've added:\n\n- AI-powered lead scoring\n- Automated email sequencing\n- Real-time company enrichment\n\nAny of these sound useful for {{companyName}}? Would love to give you a quick walkthrough.\n\nBest,\nFloeey Team",
        type: "follow-up",
      },
      {
        id: "step-010",
        order: 3,
        delayDays: 7,
        subject: "No hard feelings, {{firstName}} :)",
        body: "Hi {{firstName}},\n\nI'll take the hint! If things change down the road and {{companyName}} is looking for a better way to manage outbound, you know where to find us.\n\nWishing you continued success!\n\nBest,\nFloeey Team",
        type: "breakup",
      },
    ],
    enrolledContactIds: [],
    createdAt: "2025-12-01T09:00:00Z",
    updatedAt: "2025-12-01T09:00:00Z",
  },
];

// ─── Email Drafts ────────────────────────────────────────────────────────────

export const mockEmailDrafts: EmailDraft[] = [
  {
    id: "email-001",
    contactId: "cont-001",
    contactName: "Sarah Chen",
    companyName: "Velora AI",
    subject: "Quick question about Velora AI's tech stack",
    body: "Hi Sarah,\n\nI noticed Velora AI is making waves in the AI/ML space and recently raised an impressive Series A.\n\nI'm reaching out because we've helped similar companies streamline their outbound workflows and I'd love to share how.\n\nWould you be open to a quick 15-minute chat this week?\n\nBest,\nFloeey Team",
    status: "sent",
    sentAt: "2025-12-02T09:00:00Z",
    openedAt: "2025-12-02T11:30:00Z",
    repliedAt: null,
    sequenceId: "seq-001",
    sequenceStep: 1,
    createdAt: "2025-12-02T08:55:00Z",
  },
  {
    id: "email-002",
    contactId: "cont-001",
    contactName: "Sarah Chen",
    companyName: "Velora AI",
    subject: "Re: Quick question about Velora AI's tech stack",
    body: "Hi Sarah,\n\nJust wanted to follow up on my previous note. I know things get busy, especially at a growing company like Velora AI.\n\nI thought you might find it interesting that we recently helped an AI/ML company reduce their lead qualification time by 60%.\n\nWould love to share more details if you're interested.\n\nBest,\nFloeey Team",
    status: "sent",
    sentAt: "2025-12-05T09:00:00Z",
    openedAt: null,
    repliedAt: null,
    sequenceId: "seq-001",
    sequenceStep: 2,
    createdAt: "2025-12-05T08:55:00Z",
  },
  {
    id: "email-003",
    contactId: "cont-004",
    contactName: "James Whitfield",
    companyName: "Stackline",
    subject: "Quick question about Stackline's tech stack",
    body: "Hi James,\n\nI noticed Stackline is making incredible strides in DevOps observability, and your Gartner recognition is well deserved.\n\nI'm reaching out because we've helped similar companies streamline their outbound workflows and I'd love to share how.\n\nWould you be open to a quick 15-minute chat this week?\n\nBest,\nFloeey Team",
    status: "opened",
    sentAt: "2025-12-03T10:00:00Z",
    openedAt: "2025-12-03T14:22:00Z",
    repliedAt: null,
    sequenceId: "seq-001",
    sequenceStep: 1,
    createdAt: "2025-12-03T09:55:00Z",
  },
  {
    id: "email-004",
    contactId: "cont-007",
    contactName: "Michael Torres",
    companyName: "Finova",
    subject: "Congrats on the funding, Michael!",
    body: "Hi Michael,\n\nCongratulations to you and the Finova team on the $92M Series C! That's an incredible milestone.\n\nAs you scale, many teams in FinTech find that their outbound processes need to evolve. We've built something that might help.\n\nWould you be open to a brief conversation about how we could support Finova's growth?\n\nBest,\nFloeey Team",
    status: "replied",
    sentAt: "2025-12-01T11:00:00Z",
    openedAt: "2025-12-01T13:15:00Z",
    repliedAt: "2025-12-02T09:30:00Z",
    sequenceId: "seq-002",
    sequenceStep: 1,
    createdAt: "2025-12-01T10:55:00Z",
  },
  {
    id: "email-005",
    contactId: "cont-010",
    contactName: "Alex Morgan",
    companyName: "ClearShield",
    subject: "Quick question about ClearShield's tech stack",
    body: "Hi Alex,\n\nI noticed ClearShield is doing impressive work in the cybersecurity space, particularly with your AI-driven endpoint protection.\n\nI'm reaching out because we've helped similar companies streamline their outbound workflows and I'd love to share how.\n\nWould you be open to a quick 15-minute chat this week?\n\nBest,\nFloeey Team",
    status: "sent",
    sentAt: "2025-12-04T09:00:00Z",
    openedAt: null,
    repliedAt: null,
    sequenceId: "seq-001",
    sequenceStep: 1,
    createdAt: "2025-12-04T08:55:00Z",
  },
  {
    id: "email-006",
    contactId: "cont-013",
    contactName: "Amanda Williams",
    companyName: "Nurtura Health",
    subject: "Congrats on the funding, Amanda!",
    body: "Hi Amanda,\n\nCongratulations to you and the Nurtura Health team on the $22M Series A! The patient engagement space is ripe for innovation.\n\nAs you scale, many teams in HealthTech find that their outbound processes need to evolve. We've built something that might help.\n\nWould you be open to a brief conversation about how we could support Nurtura Health's growth?\n\nBest,\nFloeey Team",
    status: "opened",
    sentAt: "2025-12-03T11:00:00Z",
    openedAt: "2025-12-04T08:45:00Z",
    repliedAt: null,
    sequenceId: "seq-002",
    sequenceStep: 1,
    createdAt: "2025-12-03T10:55:00Z",
  },
  {
    id: "email-007",
    contactId: "cont-016",
    contactName: "Ryan Mitchell",
    companyName: "Amplifi Data",
    subject: "First-party data and outbound — a natural fit?",
    body: "Hi Ryan,\n\nI've been following Amplifi Data's work on B2B customer data unification and find it fascinating. Given your focus on first-party data, I thought you'd appreciate how Floeey approaches lead enrichment.\n\nWould you be up for a quick chat? I think there could be some interesting synergies.\n\nBest,\nFloeey Team",
    status: "draft",
    sentAt: null,
    openedAt: null,
    repliedAt: null,
    sequenceId: null,
    sequenceStep: null,
    createdAt: "2025-12-06T10:00:00Z",
  },
  {
    id: "email-008",
    contactId: "cont-019",
    contactName: "Oliver Hartley",
    companyName: "Nimbus Cloud",
    subject: "Quick question about Nimbus Cloud's tech stack",
    body: "Hi Oliver,\n\nI noticed Nimbus Cloud is solving a critical problem for engineering teams managing multi-cloud infrastructure.\n\nI'm reaching out because we've helped similar companies streamline their outbound workflows and I'd love to share how.\n\nWould you be open to a quick 15-minute chat this week?\n\nBest,\nFloeey Team",
    status: "scheduled",
    sentAt: null,
    openedAt: null,
    repliedAt: null,
    sequenceId: "seq-001",
    sequenceStep: 1,
    createdAt: "2025-12-06T11:00:00Z",
  },
  {
    id: "email-009",
    contactId: "cont-022",
    contactName: "Maya Kapoor",
    companyName: "TalentForge",
    subject: "Quick question about TalentForge's tech stack",
    body: "Hi Maya,\n\nI noticed TalentForge is reinventing technical hiring with AI-powered skills matching. Really impressive work.\n\nI'm reaching out because we've helped similar companies streamline their outbound workflows and I'd love to share how.\n\nWould you be open to a quick 15-minute chat this week?\n\nBest,\nFloeey Team",
    status: "sent",
    sentAt: "2025-12-05T10:00:00Z",
    openedAt: "2025-12-05T16:10:00Z",
    repliedAt: null,
    sequenceId: "seq-001",
    sequenceStep: 1,
    createdAt: "2025-12-05T09:55:00Z",
  },
  {
    id: "email-010",
    contactId: "cont-028",
    contactName: "Lukas Weber",
    companyName: "GreenGrid",
    subject: "Congrats on the funding, Lukas!",
    body: "Hi Lukas,\n\nCongratulations to you and the GreenGrid team on the $2.5M pre-seed and the EU Green Innovation Award! What an exciting start.\n\nAs you grow, many teams in Clean Energy find that their outbound processes need to evolve. We've built something that might help.\n\nWould you be open to a brief conversation about how we could support GreenGrid's growth?\n\nBest,\nFloeey Team",
    status: "draft",
    sentAt: null,
    openedAt: null,
    repliedAt: null,
    sequenceId: "seq-002",
    sequenceStep: 1,
    createdAt: "2025-12-06T14:00:00Z",
  },
];

// ─── Dashboard Stats ─────────────────────────────────────────────────────────

export const mockDashboardStats: DashboardStats = {
  totalCompanies: 10,
  totalContacts: 30,
  emailsSentThisWeek: 7,
  emailsSentTotal: 42,
  openRate: 58.3,
  replyRate: 12.5,
  pipelineStages: [
    { name: "New Lead", count: 12, color: "#6b7280" },
    { name: "Contacted", count: 8, color: "#3b82f6" },
    { name: "Engaged", count: 5, color: "#8b5cf6" },
    { name: "Qualified", count: 3, color: "#f59e0b" },
    { name: "Proposal Sent", count: 1, color: "#f97316" },
    { name: "Negotiation", count: 1, color: "#ec4899" },
    { name: "Closed Won", count: 0, color: "#10b981" },
    { name: "Closed Lost", count: 0, color: "#ef4444" },
  ],
};

// ─── Activity Feed ───────────────────────────────────────────────────────────

export const mockActivityItems: ActivityItem[] = [
  {
    id: "act-001",
    type: "email_replied",
    description: "Michael Torres replied to your email",
    timestamp: "2025-12-06T09:30:00Z",
    contactName: "Michael Torres",
    companyName: "Finova",
  },
  {
    id: "act-002",
    type: "company_enriched",
    description: "GreenGrid company data was enriched",
    timestamp: "2025-12-06T12:00:00Z",
    companyName: "GreenGrid",
  },
  {
    id: "act-003",
    type: "email_opened",
    description: "Maya Kapoor opened your email",
    timestamp: "2025-12-05T16:10:00Z",
    contactName: "Maya Kapoor",
    companyName: "TalentForge",
  },
  {
    id: "act-004",
    type: "email_sent",
    description: "Follow-up email sent to Sarah Chen",
    timestamp: "2025-12-05T09:00:00Z",
    contactName: "Sarah Chen",
    companyName: "Velora AI",
  },
  {
    id: "act-005",
    type: "lead_added",
    description: "GreenGrid added as a new lead",
    timestamp: "2025-12-01T10:00:00Z",
    companyName: "GreenGrid",
  },
  {
    id: "act-006",
    type: "email_opened",
    description: "Amanda Williams opened your email",
    timestamp: "2025-12-04T08:45:00Z",
    contactName: "Amanda Williams",
    companyName: "Nurtura Health",
  },
  {
    id: "act-007",
    type: "email_sent",
    description: "Initial outreach sent to Alex Morgan",
    timestamp: "2025-12-04T09:00:00Z",
    contactName: "Alex Morgan",
    companyName: "ClearShield",
  },
  {
    id: "act-008",
    type: "company_enriched",
    description: "TalentForge company data was enriched",
    timestamp: "2025-12-06T08:30:00Z",
    companyName: "TalentForge",
  },
  {
    id: "act-009",
    type: "lead_added",
    description: "TalentForge added as a new lead",
    timestamp: "2025-11-30T09:00:00Z",
    companyName: "TalentForge",
  },
  {
    id: "act-010",
    type: "email_opened",
    description: "James Whitfield opened your email",
    timestamp: "2025-12-03T14:22:00Z",
    contactName: "James Whitfield",
    companyName: "Stackline",
  },
];
